export const DEFAULT_HTTP_REQUEST_ID_HEADER = "x-request-id";
export const DEFAULT_HTTP_REQUEST_ID_FALLBACKS = ["x-correlation-id"];

export const HEADERS_PARAMS = {
	REQUEST_ID: DEFAULT_HTTP_REQUEST_ID_HEADER,
	FALLBACKS: DEFAULT_HTTP_REQUEST_ID_FALLBACKS,
};
